server:
  servlet.context-path: '/authorization'
spring:
  datasource:
    url: jdbc:mariadb://localhost/authorization?useSSL=false
    username: auth
    password: auth
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties.hibernate.dialect: org.hibernate.dialect.MariaDB103Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: info.brozartapps
    password: BrozartApps1
    properties.mail.smtp:
      auth: true
      starttls.enable: true
  profiles:
    active: development
---
spring:
  profiles: development
server:
  port: 8080
