server:
  port: 8081
  servlet.context-path: '/authorization'
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/authorization?createDatabaseIfNotExist=true&useSSL=false
    username: pokemon
    password: pokemon
  jpa:
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl